/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested, IsDate } from "class-validator";
import { CompanyWhereUniqueInput } from "../../company/base/CompanyWhereUniqueInput";
import { Type } from "class-transformer";
import { EmployeeCreateNestedManyWithoutMaintRepairsInput } from "./EmployeeCreateNestedManyWithoutMaintRepairsInput";
import { EquidevWhereUniqueInput } from "../../equidev/base/EquidevWhereUniqueInput";
@InputType()
class MaintRepairCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  actionTaken?: string | null;

  @ApiProperty({
    required: false,
    type: () => CompanyWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CompanyWhereUniqueInput)
  @IsOptional()
  @Field(() => CompanyWhereUniqueInput, {
    nullable: true,
  })
  companyId?: CompanyWhereUniqueInput | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  dateOfCeoApproval?: Date | null;

  @ApiProperty({
    required: false,
    type: () => EmployeeCreateNestedManyWithoutMaintRepairsInput,
  })
  @ValidateNested()
  @Type(() => EmployeeCreateNestedManyWithoutMaintRepairsInput)
  @IsOptional()
  @Field(() => EmployeeCreateNestedManyWithoutMaintRepairsInput, {
    nullable: true,
  })
  employeeId?: EmployeeCreateNestedManyWithoutMaintRepairsInput;

  @ApiProperty({
    required: false,
    type: () => EquidevWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => EquidevWhereUniqueInput)
  @IsOptional()
  @Field(() => EquidevWhereUniqueInput, {
    nullable: true,
  })
  equipmentId?: EquidevWhereUniqueInput | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  faultType!: string;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  lasttimeOfGoodOperation?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  nameOfBmeApprovedMaintClearance?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  nameOfTechMaintainEq?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  possibleCause?: string | null;
}
export { MaintRepairCreateInput };
