/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateMaintRepairArgs } from "./CreateMaintRepairArgs";
import { UpdateMaintRepairArgs } from "./UpdateMaintRepairArgs";
import { DeleteMaintRepairArgs } from "./DeleteMaintRepairArgs";
import { MaintRepairFindManyArgs } from "./MaintRepairFindManyArgs";
import { MaintRepairFindUniqueArgs } from "./MaintRepairFindUniqueArgs";
import { MaintRepair } from "./MaintRepair";
import { EmployeeFindManyArgs } from "../../employee/base/EmployeeFindManyArgs";
import { Employee } from "../../employee/base/Employee";
import { Company } from "../../company/base/Company";
import { Equidev } from "../../equidev/base/Equidev";
import { MaintRepairService } from "../maintRepair.service";

@graphql.Resolver(() => MaintRepair)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class MaintRepairResolverBase {
  constructor(
    protected readonly service: MaintRepairService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "MaintRepair",
    action: "read",
    possession: "any",
  })
  async _maintRepairsMeta(
    @graphql.Args() args: MaintRepairFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [MaintRepair])
  @nestAccessControl.UseRoles({
    resource: "MaintRepair",
    action: "read",
    possession: "any",
  })
  async maintRepairs(
    @graphql.Args() args: MaintRepairFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<MaintRepair[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "MaintRepair",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => MaintRepair, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "MaintRepair",
    action: "read",
    possession: "own",
  })
  async maintRepair(
    @graphql.Args() args: MaintRepairFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<MaintRepair | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "MaintRepair",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => MaintRepair)
  @nestAccessControl.UseRoles({
    resource: "MaintRepair",
    action: "create",
    possession: "any",
  })
  async createMaintRepair(
    @graphql.Args() args: CreateMaintRepairArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<MaintRepair> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "MaintRepair",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"MaintRepair"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        companyId: args.data.companyId
          ? {
              connect: args.data.companyId,
            }
          : undefined,

        equipmentId: args.data.equipmentId
          ? {
              connect: args.data.equipmentId,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => MaintRepair)
  @nestAccessControl.UseRoles({
    resource: "MaintRepair",
    action: "update",
    possession: "any",
  })
  async updateMaintRepair(
    @graphql.Args() args: UpdateMaintRepairArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<MaintRepair | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "MaintRepair",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"MaintRepair"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          companyId: args.data.companyId
            ? {
                connect: args.data.companyId,
              }
            : undefined,

          equipmentId: args.data.equipmentId
            ? {
                connect: args.data.equipmentId,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => MaintRepair)
  @nestAccessControl.UseRoles({
    resource: "MaintRepair",
    action: "delete",
    possession: "any",
  })
  async deleteMaintRepair(
    @graphql.Args() args: DeleteMaintRepairArgs
  ): Promise<MaintRepair | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Employee])
  @nestAccessControl.UseRoles({
    resource: "MaintRepair",
    action: "read",
    possession: "any",
  })
  async employeeId(
    @graphql.Parent() parent: MaintRepair,
    @graphql.Args() args: EmployeeFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Employee[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Employee",
    });
    const results = await this.service.findEmployeeId(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }

  @graphql.ResolveField(() => Company, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "MaintRepair",
    action: "read",
    possession: "any",
  })
  async companyId(
    @graphql.Parent() parent: MaintRepair,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Company | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Company",
    });
    const result = await this.service.getCompanyId(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.ResolveField(() => Equidev, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "MaintRepair",
    action: "read",
    possession: "any",
  })
  async equipmentId(
    @graphql.Parent() parent: MaintRepair,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Equidev | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Equidev",
    });
    const result = await this.service.getEquipmentId(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
