/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateInstallationArgs } from "./CreateInstallationArgs";
import { UpdateInstallationArgs } from "./UpdateInstallationArgs";
import { DeleteInstallationArgs } from "./DeleteInstallationArgs";
import { InstallationFindManyArgs } from "./InstallationFindManyArgs";
import { InstallationFindUniqueArgs } from "./InstallationFindUniqueArgs";
import { Installation } from "./Installation";
import { EmployeeFindManyArgs } from "../../employee/base/EmployeeFindManyArgs";
import { Employee } from "../../employee/base/Employee";
import { Company } from "../../company/base/Company";
import { Equidev } from "../../equidev/base/Equidev";
import { InstallationService } from "../installation.service";

@graphql.Resolver(() => Installation)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class InstallationResolverBase {
  constructor(
    protected readonly service: InstallationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Installation",
    action: "read",
    possession: "any",
  })
  async _installationsMeta(
    @graphql.Args() args: InstallationFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [Installation])
  @nestAccessControl.UseRoles({
    resource: "Installation",
    action: "read",
    possession: "any",
  })
  async installations(
    @graphql.Args() args: InstallationFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Installation[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Installation",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => Installation, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Installation",
    action: "read",
    possession: "own",
  })
  async installation(
    @graphql.Args() args: InstallationFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Installation | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Installation",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => Installation)
  @nestAccessControl.UseRoles({
    resource: "Installation",
    action: "create",
    possession: "any",
  })
  async createInstallation(
    @graphql.Args() args: CreateInstallationArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Installation> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "Installation",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Installation"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        companyId: {
          connect: args.data.companyId,
        },

        equipmentId: args.data.equipmentId
          ? {
              connect: args.data.equipmentId,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Installation)
  @nestAccessControl.UseRoles({
    resource: "Installation",
    action: "update",
    possession: "any",
  })
  async updateInstallation(
    @graphql.Args() args: UpdateInstallationArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Installation | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Installation",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Installation"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          companyId: {
            connect: args.data.companyId,
          },

          equipmentId: args.data.equipmentId
            ? {
                connect: args.data.equipmentId,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Installation)
  @nestAccessControl.UseRoles({
    resource: "Installation",
    action: "delete",
    possession: "any",
  })
  async deleteInstallation(
    @graphql.Args() args: DeleteInstallationArgs
  ): Promise<Installation | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Employee])
  @nestAccessControl.UseRoles({
    resource: "Installation",
    action: "read",
    possession: "any",
  })
  async employeeId(
    @graphql.Parent() parent: Installation,
    @graphql.Args() args: EmployeeFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Employee[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Employee",
    });
    const results = await this.service.findEmployeeId(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }

  @graphql.ResolveField(() => Company, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Installation",
    action: "read",
    possession: "any",
  })
  async companyId(
    @graphql.Parent() parent: Installation,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Company | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Company",
    });
    const result = await this.service.getCompanyId(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.ResolveField(() => Equidev, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Installation",
    action: "read",
    possession: "any",
  })
  async equipmentId(
    @graphql.Parent() parent: Installation,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Equidev | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Equidev",
    });
    const result = await this.service.getEquipmentId(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
