/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsDate,
  IsString,
  IsOptional,
  ValidateNested,
  IsEnum,
  IsInt,
} from "class-validator";
import { Type } from "class-transformer";
import { Employee } from "../../employee/base/Employee";
import { EnumTaskPlannerPriorityLevel } from "./EnumTaskPlannerPriorityLevel";
import { EnumTaskPlannerTaskStatus } from "./EnumTaskPlannerTaskStatus";
import { Ticket } from "../../ticket/base/Ticket";
@ObjectType()
class TaskPlanner {
  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  employeeAssigned!: string | null;

  @ApiProperty({
    required: false,
    type: () => Employee,
  })
  @ValidateNested()
  @Type(() => Employee)
  @IsOptional()
  employeeid?: Employee | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    enum: EnumTaskPlannerPriorityLevel,
  })
  @IsEnum(EnumTaskPlannerPriorityLevel)
  @IsOptional()
  @Field(() => EnumTaskPlannerPriorityLevel, {
    nullable: true,
  })
  priorityLevel?: "High" | "Middium" | "Low" | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  taskEndDate!: Date;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  taskStartDate!: Date;

  @ApiProperty({
    required: false,
    enum: EnumTaskPlannerTaskStatus,
  })
  @IsEnum(EnumTaskPlannerTaskStatus)
  @IsOptional()
  @Field(() => EnumTaskPlannerTaskStatus, {
    nullable: true,
  })
  taskStatus?: "Open" | "Done" | "Closed" | null;

  @ApiProperty({
    required: false,
    type: () => Ticket,
  })
  @ValidateNested()
  @Type(() => Ticket)
  @IsOptional()
  ticketId?: Ticket | null;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsInt()
  @Field(() => Number)
  ticketNumber!: number;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}
export { TaskPlanner };
