/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateEquipmentSaleArgs } from "./CreateEquipmentSaleArgs";
import { UpdateEquipmentSaleArgs } from "./UpdateEquipmentSaleArgs";
import { DeleteEquipmentSaleArgs } from "./DeleteEquipmentSaleArgs";
import { EquipmentSaleFindManyArgs } from "./EquipmentSaleFindManyArgs";
import { EquipmentSaleFindUniqueArgs } from "./EquipmentSaleFindUniqueArgs";
import { EquipmentSale } from "./EquipmentSale";
import { EquidevFindManyArgs } from "../../equidev/base/EquidevFindManyArgs";
import { Equidev } from "../../equidev/base/Equidev";
import { Company } from "../../company/base/Company";
import { Employee } from "../../employee/base/Employee";
import { EquipmentSaleService } from "../equipmentSale.service";

@graphql.Resolver(() => EquipmentSale)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class EquipmentSaleResolverBase {
  constructor(
    protected readonly service: EquipmentSaleService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "EquipmentSale",
    action: "read",
    possession: "any",
  })
  async _equipmentSalesMeta(
    @graphql.Args() args: EquipmentSaleFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [EquipmentSale])
  @nestAccessControl.UseRoles({
    resource: "EquipmentSale",
    action: "read",
    possession: "any",
  })
  async equipmentSales(
    @graphql.Args() args: EquipmentSaleFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<EquipmentSale[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "EquipmentSale",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => EquipmentSale, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "EquipmentSale",
    action: "read",
    possession: "own",
  })
  async equipmentSale(
    @graphql.Args() args: EquipmentSaleFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<EquipmentSale | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "EquipmentSale",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => EquipmentSale)
  @nestAccessControl.UseRoles({
    resource: "EquipmentSale",
    action: "create",
    possession: "any",
  })
  async createEquipmentSale(
    @graphql.Args() args: CreateEquipmentSaleArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<EquipmentSale> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "EquipmentSale",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"EquipmentSale"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        companyId: args.data.companyId
          ? {
              connect: args.data.companyId,
            }
          : undefined,

        employeeId: args.data.employeeId
          ? {
              connect: args.data.employeeId,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => EquipmentSale)
  @nestAccessControl.UseRoles({
    resource: "EquipmentSale",
    action: "update",
    possession: "any",
  })
  async updateEquipmentSale(
    @graphql.Args() args: UpdateEquipmentSaleArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<EquipmentSale | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "EquipmentSale",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"EquipmentSale"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          companyId: args.data.companyId
            ? {
                connect: args.data.companyId,
              }
            : undefined,

          employeeId: args.data.employeeId
            ? {
                connect: args.data.employeeId,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => EquipmentSale)
  @nestAccessControl.UseRoles({
    resource: "EquipmentSale",
    action: "delete",
    possession: "any",
  })
  async deleteEquipmentSale(
    @graphql.Args() args: DeleteEquipmentSaleArgs
  ): Promise<EquipmentSale | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Equidev])
  @nestAccessControl.UseRoles({
    resource: "EquipmentSale",
    action: "read",
    possession: "any",
  })
  async equipmentId(
    @graphql.Parent() parent: EquipmentSale,
    @graphql.Args() args: EquidevFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Equidev[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Equidev",
    });
    const results = await this.service.findEquipmentId(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }

  @graphql.ResolveField(() => Company, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "EquipmentSale",
    action: "read",
    possession: "any",
  })
  async companyId(
    @graphql.Parent() parent: EquipmentSale,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Company | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Company",
    });
    const result = await this.service.getCompanyId(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.ResolveField(() => Employee, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "EquipmentSale",
    action: "read",
    possession: "any",
  })
  async employeeId(
    @graphql.Parent() parent: EquipmentSale,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Employee | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Employee",
    });
    const result = await this.service.getEmployeeId(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
