/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "nestjs-prisma";

import {
  Prisma,
  Company,
  Employee,
  Equidev,
  EquipmentSale,
  Installation,
  MaintRepair,
  SparePart,
  Ticket,
} from "@prisma/client";

export class CompanyServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.CompanyFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.CompanyFindManyArgs>
  ): Promise<number> {
    return this.prisma.company.count(args);
  }

  async findMany<T extends Prisma.CompanyFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.CompanyFindManyArgs>
  ): Promise<Company[]> {
    return this.prisma.company.findMany(args);
  }
  async findOne<T extends Prisma.CompanyFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.CompanyFindUniqueArgs>
  ): Promise<Company | null> {
    return this.prisma.company.findUnique(args);
  }
  async create<T extends Prisma.CompanyCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.CompanyCreateArgs>
  ): Promise<Company> {
    return this.prisma.company.create<T>(args);
  }
  async update<T extends Prisma.CompanyUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.CompanyUpdateArgs>
  ): Promise<Company> {
    return this.prisma.company.update<T>(args);
  }
  async delete<T extends Prisma.CompanyDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.CompanyDeleteArgs>
  ): Promise<Company> {
    return this.prisma.company.delete(args);
  }

  async findEmployees(
    parentId: string,
    args: Prisma.EmployeeFindManyArgs
  ): Promise<Employee[]> {
    return this.prisma.company
      .findUnique({
        where: { id: parentId },
      })
      .employees(args);
  }

  async findEquipments(
    parentId: string,
    args: Prisma.EquidevFindManyArgs
  ): Promise<Equidev[]> {
    return this.prisma.company
      .findUnique({
        where: { id: parentId },
      })
      .equipments(args);
  }

  async findEquipmentSales(
    parentId: string,
    args: Prisma.EquipmentSaleFindManyArgs
  ): Promise<EquipmentSale[]> {
    return this.prisma.company
      .findUnique({
        where: { id: parentId },
      })
      .equipmentSales(args);
  }

  async findInstallations(
    parentId: string,
    args: Prisma.InstallationFindManyArgs
  ): Promise<Installation[]> {
    return this.prisma.company
      .findUnique({
        where: { id: parentId },
      })
      .installations(args);
  }

  async findMaintRepairs(
    parentId: string,
    args: Prisma.MaintRepairFindManyArgs
  ): Promise<MaintRepair[]> {
    return this.prisma.company
      .findUnique({
        where: { id: parentId },
      })
      .maintRepairs(args);
  }

  async findSpareParts(
    parentId: string,
    args: Prisma.SparePartFindManyArgs
  ): Promise<SparePart[]> {
    return this.prisma.company
      .findUnique({
        where: { id: parentId },
      })
      .spareParts(args);
  }

  async findTickets(
    parentId: string,
    args: Prisma.TicketFindManyArgs
  ): Promise<Ticket[]> {
    return this.prisma.company
      .findUnique({
        where: { id: parentId },
      })
      .tickets(args);
  }
}
