/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateSparePartArgs } from "./CreateSparePartArgs";
import { UpdateSparePartArgs } from "./UpdateSparePartArgs";
import { DeleteSparePartArgs } from "./DeleteSparePartArgs";
import { SparePartFindManyArgs } from "./SparePartFindManyArgs";
import { SparePartFindUniqueArgs } from "./SparePartFindUniqueArgs";
import { SparePart } from "./SparePart";
import { Company } from "../../company/base/Company";
import { Equidev } from "../../equidev/base/Equidev";
import { SparePartService } from "../sparePart.service";

@graphql.Resolver(() => SparePart)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class SparePartResolverBase {
  constructor(
    protected readonly service: SparePartService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "SparePart",
    action: "read",
    possession: "any",
  })
  async _sparePartsMeta(
    @graphql.Args() args: SparePartFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [SparePart])
  @nestAccessControl.UseRoles({
    resource: "SparePart",
    action: "read",
    possession: "any",
  })
  async spareParts(
    @graphql.Args() args: SparePartFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<SparePart[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "SparePart",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => SparePart, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "SparePart",
    action: "read",
    possession: "own",
  })
  async sparePart(
    @graphql.Args() args: SparePartFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<SparePart | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "SparePart",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => SparePart)
  @nestAccessControl.UseRoles({
    resource: "SparePart",
    action: "create",
    possession: "any",
  })
  async createSparePart(
    @graphql.Args() args: CreateSparePartArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<SparePart> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "SparePart",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"SparePart"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        companyId: args.data.companyId
          ? {
              connect: args.data.companyId,
            }
          : undefined,

        equipmentId: args.data.equipmentId
          ? {
              connect: args.data.equipmentId,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => SparePart)
  @nestAccessControl.UseRoles({
    resource: "SparePart",
    action: "update",
    possession: "any",
  })
  async updateSparePart(
    @graphql.Args() args: UpdateSparePartArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<SparePart | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "SparePart",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"SparePart"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          companyId: args.data.companyId
            ? {
                connect: args.data.companyId,
              }
            : undefined,

          equipmentId: args.data.equipmentId
            ? {
                connect: args.data.equipmentId,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => SparePart)
  @nestAccessControl.UseRoles({
    resource: "SparePart",
    action: "delete",
    possession: "any",
  })
  async deleteSparePart(
    @graphql.Args() args: DeleteSparePartArgs
  ): Promise<SparePart | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Company, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "SparePart",
    action: "read",
    possession: "any",
  })
  async companyId(
    @graphql.Parent() parent: SparePart,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Company | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Company",
    });
    const result = await this.service.getCompanyId(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.ResolveField(() => Equidev, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "SparePart",
    action: "read",
    possession: "any",
  })
  async equipmentId(
    @graphql.Parent() parent: SparePart,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Equidev | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Equidev",
    });
    const result = await this.service.getEquipmentId(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
