/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CompanyWhereUniqueInput } from "../../company/base/CompanyWhereUniqueInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  IsBoolean,
  IsDate,
} from "class-validator";
import { Type } from "class-transformer";
import { EquipmentSaleWhereUniqueInput } from "../../equipmentSale/base/EquipmentSaleWhereUniqueInput";
import { InstallationWhereUniqueInput } from "../../installation/base/InstallationWhereUniqueInput";
import { MaintRepairWhereUniqueInput } from "../../maintRepair/base/MaintRepairWhereUniqueInput";
import { SparePartUpdateManyWithoutEquidevsInput } from "./SparePartUpdateManyWithoutEquidevsInput";
import { TicketUpdateManyWithoutEquidevsInput } from "./TicketUpdateManyWithoutEquidevsInput";
@InputType()
class EquidevUpdateInput {
  @ApiProperty({
    required: false,
    type: () => CompanyWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CompanyWhereUniqueInput)
  @IsOptional()
  @Field(() => CompanyWhereUniqueInput, {
    nullable: true,
  })
  companyId?: CompanyWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  countryOfOrign?: string | null;

  @ApiProperty({
    required: false,
    type: () => EquipmentSaleWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => EquipmentSaleWhereUniqueInput)
  @IsOptional()
  @Field(() => EquipmentSaleWhereUniqueInput, {
    nullable: true,
  })
  equipmentSales?: EquipmentSaleWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  hasSparePart?: boolean | null;

  @ApiProperty({
    required: false,
    type: () => InstallationWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => InstallationWhereUniqueInput)
  @IsOptional()
  @Field(() => InstallationWhereUniqueInput, {
    nullable: true,
  })
  installations?: InstallationWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => MaintRepairWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => MaintRepairWhereUniqueInput)
  @IsOptional()
  @Field(() => MaintRepairWhereUniqueInput, {
    nullable: true,
  })
  maintRepairs?: MaintRepairWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  manufacturerName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  model?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  serialNumber?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  shipmentArrivalDate?: Date | null;

  @ApiProperty({
    required: false,
    type: () => SparePartUpdateManyWithoutEquidevsInput,
  })
  @ValidateNested()
  @Type(() => SparePartUpdateManyWithoutEquidevsInput)
  @IsOptional()
  @Field(() => SparePartUpdateManyWithoutEquidevsInput, {
    nullable: true,
  })
  spareParts?: SparePartUpdateManyWithoutEquidevsInput;

  @ApiProperty({
    required: false,
    type: () => TicketUpdateManyWithoutEquidevsInput,
  })
  @ValidateNested()
  @Type(() => TicketUpdateManyWithoutEquidevsInput)
  @IsOptional()
  @Field(() => TicketUpdateManyWithoutEquidevsInput, {
    nullable: true,
  })
  tickets?: TicketUpdateManyWithoutEquidevsInput;
}
export { EquidevUpdateInput };
