/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "nestjs-prisma";

import {
  Prisma,
  Equidev,
  MaintRepair,
  SparePart,
  Ticket,
  Company,
  EquipmentSale,
  Installation,
} from "@prisma/client";

export class EquidevServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.EquidevFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.EquidevFindManyArgs>
  ): Promise<number> {
    return this.prisma.equidev.count(args);
  }

  async findMany<T extends Prisma.EquidevFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.EquidevFindManyArgs>
  ): Promise<Equidev[]> {
    return this.prisma.equidev.findMany(args);
  }
  async findOne<T extends Prisma.EquidevFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.EquidevFindUniqueArgs>
  ): Promise<Equidev | null> {
    return this.prisma.equidev.findUnique(args);
  }
  async create<T extends Prisma.EquidevCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.EquidevCreateArgs>
  ): Promise<Equidev> {
    return this.prisma.equidev.create<T>(args);
  }
  async update<T extends Prisma.EquidevUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.EquidevUpdateArgs>
  ): Promise<Equidev> {
    return this.prisma.equidev.update<T>(args);
  }
  async delete<T extends Prisma.EquidevDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.EquidevDeleteArgs>
  ): Promise<Equidev> {
    return this.prisma.equidev.delete(args);
  }

  async findMaintRepairs(
    parentId: string,
    args: Prisma.MaintRepairFindManyArgs
  ): Promise<MaintRepair[]> {
    return this.prisma.equidev
      .findUnique({
        where: { id: parentId },
      })
      .maintRepairs(args);
  }

  async findSpareParts(
    parentId: string,
    args: Prisma.SparePartFindManyArgs
  ): Promise<SparePart[]> {
    return this.prisma.equidev
      .findUnique({
        where: { id: parentId },
      })
      .spareParts(args);
  }

  async findTickets(
    parentId: string,
    args: Prisma.TicketFindManyArgs
  ): Promise<Ticket[]> {
    return this.prisma.equidev
      .findUnique({
        where: { id: parentId },
      })
      .tickets(args);
  }

  async getCompanyId(parentId: string): Promise<Company | null> {
    return this.prisma.equidev
      .findUnique({
        where: { id: parentId },
      })
      .companyId();
  }

  async getEquipmentSales(parentId: string): Promise<EquipmentSale | null> {
    return this.prisma.equidev
      .findUnique({
        where: { id: parentId },
      })
      .equipmentSales();
  }

  async getInstallations(parentId: string): Promise<Installation | null> {
    return this.prisma.equidev
      .findUnique({
        where: { id: parentId },
      })
      .installations();
  }
}
